[package]
name = "tiny_http"
version = "0.7.0"
authors = ["pierre.krieger1708@gmail.com",
           "Corey Farwell <coreyf@rwell.org>"]
description = "Low level HTTP server library"
documentation = "https://tiny-http.github.io/tiny-http/tiny_http/index.html"
keywords = ["http", "server", "web"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/tiny-http/tiny-http"

[features]
default = []
ssl = ["openssl"]

[dependencies]
ascii = "1.0"
chunked_transfer = "1"
openssl = { version = "0.10", optional = true }
url = "2"
chrono = "0.4"
log = "0.4"

[dev-dependencies]
rustc-serialize = "0.3"
sha1 = "0.6.0"
fdlimit = "0.1"
