[package]
name = "tiny_http"
version = "0.4.1"
authors = ["pierre.krieger1708@gmail.com",
           "Corey Farwell <coreyf@rwell.org>"]
description = "Low level HTTP server library"
documentation = "https://frewsxcv.github.io/tiny-http/tiny_http/index.html"
keywords = ["http", "server", "web"]
license = "Apache-2.0"
repository = "https://github.com/frewsxcv/tiny-http"

[features]
default = []
ssl = ["openssl"]

[dependencies]
ascii = "0.5"
chunked_transfer = "0.3"
encoding = "0.2"
openssl = { version = "0.7", optional = true }
rustc-serialize = "0.3"
url = "0.2"
chrono = "0.2.15"
